- .circleci/config.yml
- project.clj
- src/metabase/driver/clickhouse.clj
- test/metabase/driver/clickhouse_test.clj
Fixes issue #3 
There are probably more elegant ways to do this, but this is how it works:
* Check-out branch `clickhouse-driver-testing` from enqueue metabase fork
* Mount clickhouse driver directory beneath `modules/drivers`
* Run backend integration tests for `DRIVERS=h2,clickhouse`
> Run the MetaBase integration tests via ClickHouse

- src/metabase/driver/clickhouse.clj
- test/metabase/driver/clickhouse_test.clj
I made an error when implementing #4 : Sometimes, empty results are included even if a specific value was searched for.
> fix is-empty comparison

- src/metabase/driver/clickhouse.clj
- test/metabase/test/data/clickhouse.clj
Try to support foreign keys #9
Failures:
expected: `2014-04-07T00:00:00.000Z`
actual: `2014-04-07T07:00:00.000Z`
quoting the test: `;; not sure why only Oracle seems to do this
(let [tz (if (= driver/*driver* :oracle) "07:00:00.000Z"  "00:00:00.000Z")]`
expected: `:columns ["id" "sum"], :rows [[1 5] [2 1] [3 8]]`
actual: `:rows [[1 270487168] [2 0] [3 1]], :columns ("id" "sum")`
expected: `[[nil "2014-04-07T00:00:00.000Z"] [nil "2014-09-18T00:00:00.000Z"]]`
actual: `[[nil "2014-04-07T07:00:00.000Z"] [nil "2014-09-18T07:00:00.000Z"]]`
```'
SELECT 
id, 
category_id, 
city_id, 
toDateTime(`--sightings.timestamp` AS `sightings.timestamp`) AS timestamp
FROM 
(
SELECT *
FROM `tupac-sightings`.sightings 
LEFT JOIN `tupac-sightings`.cities AS cities__via__city_id ON city_id = …
```
> Try to enable Foreign Keys #9

- README.md
- resources/metabase-plugin.yaml
- test/metabase/driver/clickhouse_test.clj
Adds Metabase's `default-advanced-options` plugin feature.
Among other things, it allows users to sync their databases daily instead of hourly.
This also brings back the JDBC connection's "additional-options", which were previously missing in the UI, and resolves https://github.com/enqueue/metabase-clickhouse-driver/issues/85.
> Add default-advanced-options plugin feature and JDBC additional options

- src/metabase/driver/clickhouse.clj
- test/metabase/driver/clickhouse_test.clj
- test/metabase/test/data/clickhouse.clj
Resolves #88 
This workaround is not required anymore with the new JDBC driver.
> Remove Booleans workaround

- .docker/config.xml
- .github/workflows/check.yml
- CONTRIBUTING.md
- README.md
- docker-compose.yml
- src/metabase/driver/clickhouse.clj
- test/metabase/driver/clickhouse_test.clj
* Fixed `now()` vs `now(TIMEZONE)` behavior. Should resolve #103 and #81 
* Added Metabase container. It is useful for smoke testing, as we can avoid raw `docker run ...` commands and have a link to the local ClickHouse container without `dockerhost` shenanigans.
> Fix TIMESTAMP_WITH_TIMEZONE behavior, add Metabase Docker container

- resources/metabase-plugin.yaml
- src/metabase/driver/clickhouse.clj
- test/metabase/driver/clickhouse_test.clj
Reflects changes introduced in https://github.com/ClickHouse/clickhouse-jdbc/commit/9be9db2f43539ef5c7a7cad1451ca678c617a63a
Related to #118 and might resolve it.
> Add use_no_proxy JDBC option

- .github/deps.edn
- test/metabase/test/data/clickhouse.clj
Allows to uncomment `datetime-binning-options-test` for CI as it does not fail now.
> Implement tx/supports-time-type? for tests

- CHANGELOG.md
- README.md
- resources/metabase-plugin.yaml
- src/metabase/driver/clickhouse.clj
- test/metabase/driver/clickhouse_test.clj
1.0.0 is our formal stable release milestone.
* Added HTTP User-Agent (via clickhouse-jdbc `client_name` setting) with the plugin info according to the [language client spec](https://docs.google.com/document/d/1924Dvy79KXIhfqKpi1EBVY3133pIdoMwgCQtZ-uhEKs/edit#heading=h.ah33hoz5xei2). For now it's just `metabase/1.0.0 clickhouse-jdbc/0.3.2-patch-11`, OS and runtime info will be appended after we upgrade to the JDBC v0.4.0 and use `product_name` setting instead.
> Add client_name JDBC setting, prepare 1.0.0 release

- CHANGELOG.md
- README.md
- resources/metabase-plugin.yaml
- src/metabase/driver/clickhouse.clj
- test/metabase/driver/clickhouse_test.clj
- test/metabase/driver/clickhouse_test_utils.clj
- test/metabase/test/data/clickhouse.clj
Resolves #123 
Fixed schema sync failure and data browser crash if one of the tables had `(Simple)AggregationFunction` type columns.
As the underlying JDBC driver version does not support these types of columns, those are now excluded from the table metadata and data browser result sets to prevent sync or data browsing errors.
> Filter (Simple)AggregateFunction columns

- .github/deps.edn
- .github/workflows/check.yml
- CHANGELOG.md
- README.md
- docker-compose.yml
- resources/metabase-plugin.yaml
- src/metabase/driver/clickhouse.clj
- test/metabase/driver/clickhouse_test.clj
- test/metabase/test/data/clickhouse.clj
* Fixed NPE that could be thrown by the driver in case of empty database name input;
* Use Metabase 0.45.2 for CI.
> Fixed NPE in case of empty dbname

- CHANGELOG.md
- README.md
- resources/metabase-plugin.yaml
- src/metabase/driver/clickhouse.clj
- test/metabase/driver/clickhouse_test.clj
- test/metabase/test/data/clickhouse.clj
Resolves #137 #121 
Adds a new "Scan all databases" UI toggle (disabled by default), which tells the driver to scan all available databases instead of only the database it is connected to.
Database input moved below host/port/username/password as it seems more logical.
As a result, we can see all the databases as schemas in the data browser:
> Add "Scan all databases" option

- CHANGELOG.md
- resources/metabase-plugin.yaml
- src/metabase/driver/clickhouse.clj
- test/metabase/driver/clickhouse_test.clj
- test/metabase/driver/clickhouse_test_utils.clj
- test/metabase/test/data/clickhouse.clj
* Now the driver is able to scan and work with `SimpleAggregateFunction` columns: those were excluded by mistake in 1.0.2.
> Scan SimpleAggregateFunction columns

- README.md
The `SimpleAggregateFunction` is supported, however, the `AggregateFunction` is not.
Correct description.
> Correct description

- .github/workflows/check.yml
- CHANGELOG.md
- docker-compose.yml
- resources/metabase-plugin.yaml
- src/metabase/driver/clickhouse.clj
- src/metabase/driver/clickhouse_nippy.clj
- test/metabase/driver/clickhouse_test.clj
- test/metabase/test/data/clickhouse.clj
Resolves #147 
Four same questions on a dashboard, each cached with [cell towers](https://clickhouse.com/docs/en/getting-started/example-datasets/cell-towers), which has `UnsignedByte`/`UnsignedShort`/`UnsignedInteger` JDBC driver values:
> Fixed Nippy error with unsigned ClickHouse types

- .github/workflows/check.yml
- CHANGELOG.md
- docker-compose.yml
- resources/metabase-plugin.yaml
- src/metabase/driver/clickhouse.clj
- test/metabase/driver/clickhouse_base_types_test.clj
- test/metabase/driver/clickhouse_test.clj
- test/metabase/test/data/clickhouse.clj
- test/metabase/test/data/datasets.sql
* Metabase 0.47 support
* Connection impersonation support (0.47 feature)
* `DateTime64` is now correctly mapped to `:type/DateTime`
* General database type -> base type mapping rework (some test scenarios were taken from https://regex101.com/r/Yahlbt/1, props to @mlosnikov)
Resolves #177 
Resolves #178 
Resolves #179
> Metabase 0.47 support, reworked base types mapping

- README.md
Adds a missing 'v' in the metabase version that prevents the instructions from failing:
```
export METABASE_VERSION=0.47.2
export METABASE_CLICKHOUSE_DRIVER_VERSION=1.2.1
mkdir -p mb/plugins && cd mb
curl -o metabase.jar https://downloads.metabase.com/$METABASE_VERSION/metabase.jar
curl -L -o plugins/ch.jar https://github.com/ClickHouse/metabase-clickhouse-driver/releases/download/$METABASE_CLICKHOUSE_DRIVER_VERSION/clickhouse.metabase-driver.jar
MB_PLUGINS_DIR=./plugins; java -jar metabase.jar
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   547  100   547    0     0   1179      0 --:--:-- --:--:-- --:--:--  1189
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload …
```
> [README] add missing v and use latest versions

- .docker/clickhouse/single_node_tls/Dockerfile
- CHANGELOG.md
- README.md
- build_docker_image.sh
- docker-compose.yml
- resources/metabase-plugin.yaml
- src/metabase/driver/clickhouse.clj
- src/metabase/driver/clickhouse_introspection.clj
- src/metabase/driver/clickhouse_qp.clj
- test/metabase/driver/clickhouse_base_types_test.clj
- test/metabase/driver/clickhouse_temporal_bucketing_test.clj
- test/metabase/driver/clickhouse_test.clj
- test/metabase/test/data/clickhouse.clj
- test/metabase/test/data/datasets.sql
* `:connection-impersonation` does not work well with clustered setups and is disabled for now, at least until we find a proper way to enforce session-level settings within clusters. Related to #192 
* Remove unnecessary CAST as timestamp calls - related to #127 
For example, now `toStartOfHour` and similar functions will not be forced to call CAST:
```sql
SELECT
` toStartOfHour ` (` default `.` wares `.` createdAt `) AS ` createdAt `,
COUNT(*) AS ` count `
FROM
` default `.` wares `
WHERE
` default `.` wares `.` createdAt ` < ` parseDateTimeBestEffort ` ('2023-09-28 00:00:00.000Z')
GROUP BY
` toStartOfHour ` (` default `.` wares `.` createdAt `)
ORDER BY
` toStartOfHour ` (` default `.` wares `.` createdAt `) ASC
```
NB1: `parseDateTimeBestEffort` here still relies on the server …
> Prepare 1.2.2

- CHANGELOG.md
- README.md
- resources/metabase-plugin.yaml
- src/metabase/driver/clickhouse.clj
- src/metabase/driver/clickhouse_introspection.clj
- test/metabase/driver/clickhouse_base_types_test.clj
- test/metabase/test/data/clickhouse.clj
- test/metabase/test/data/datasets.sql
Resolves #203 
DB -> base type introspection is rewritten to be as simple as possible, without regex.
> Fix LowCardinality(Nullable) types introspection

- .docker/clickhouse/single_node/users.xml
- resources/metabase-plugin.yaml
- src/metabase/driver/clickhouse.clj
- test/metabase/driver/clickhouse_test.clj
- test/metabase/test/data/clickhouse.clj
- test/metabase/test/data/datasets.sql
Related to #212 - trying a different approach with the `can-connect` method implementation.
> Simplify can-connect method

- .github/workflows/check.yml
- src/metabase/driver/clickhouse.clj
- test/metabase/driver/clickhouse_test.clj
- test/metabase/test/data/clickhouse.clj
Issue tracking CSV uploads: https://github.com/ClickHouse/metabase-clickhouse-driver/issues/230
This PR adds support for the `uploads` driver feature for ClickHouse. The feature is currently only supported for ClickHouse Cloud. It requires Metabase x.49.11 to work correctly.
Limitations:
- OffsetDateTime values in the CSV e.g. "2022-01-01T00:00:00+01" are inserted as strings, while in other officially supported drivers they would be inserted as a type with a time zone. This is blocked by #200
- There is no automatically generated primary key column. This is because ClickHouse doesn't support an auto-incrementing type like `SERIAL` in PostgreSQL.
Delete items not relevant to your PR:
> CSV uploads for ClickHouse Cloud

- src/metabase/driver/clickhouse.clj
- test/metabase/driver/clickhouse_test.clj
This PR fixes two issues:
1. Fixes https://github.com/ClickHouse/metabase-clickhouse-driver/issues/237. This is tested in the Metabase repo with a new test added by https://github.com/metabase/metabase/pull/42918
2. Fixes an issue introduced by https://github.com/ClickHouse/metabase-clickhouse-driver/pull/236 where if the DB details don't lead to a successful connection, much of Metabase will be rendered completely unusable because of an uncaught exception from the new `cloud?` function.
> CSV Uploads: catch failed connections and fix duplicate inserts

- CHANGELOG.md
- src/metabase/driver/clickhouse.clj
- src/metabase/driver/clickhouse_qp.clj
Resolves #254, related to #200.
This PR enables the `:convert-timezone` ([docs](https://www.metabase.com/docs/latest/questions/query-builder/expressions/converttimezone)) Metabase feature.
> Enable the `:convert-timezone` driver feature

- .docker/clickhouse/single_node_tls/Dockerfile
- CHANGELOG.md
- docker-compose.yml
- resources/metabase-plugin.yaml
- src/metabase/driver/clickhouse.clj
- test/metabase/test/data/clickhouse.clj
Related: #260 
The analyzer probably fixes it. It used to be disabled only because of this issue: https://github.com/ClickHouse/ClickHouse/issues/64487
The tests are working as expected, even when the analyzer is enabled.
> Remove `allow_experimental_analyzer=0` setting

- src/metabase/driver/clickhouse.clj
Closes https://github.com/metabase/metabase/issues/47007
Without this change Metabase will throw the following error when uploading a CSV with a datetime with an offset value:
```
class java.time.OffsetDateTime` cannot be cast to class `java.lang.String`
```
This is because we were missing a case in the insert method, and it was falling through the the catch all case. The first fix is to add an explicit case for this type to fix the JDBC integration.
The second fix is to update the config for how we map CSV columns to database types in particular. Since Clickhouse does not preserve the input offset, we made the product choice to keep these values as their raw input string. By returning `nil` for this type we can trigger this behavior.
I am not sure how to get this tested (incl the CSV …
> Fix error uploading offset datetime

- src/metabase/driver/clickhouse.clj
- test/metabase/driver/clickhouse_impersonation_test.clj
Closes https://github.com/ClickHouse/metabase-clickhouse-driver/issues/262
- Split roles and add quotes around them if needed, before setting the role
Delete items not relevant to your PR:
> Support quoted roles (#262)

- CHANGELOG.md
- resources/metabase-plugin.yaml
- src/metabase/driver/clickhouse.clj
- test/metabase/test/data/clickhouse.clj
> Release 1.50.5

- src/metabase/driver/clickhouse.clj
Unfortunately there was a regression in [this commit](https://github.com/ClickHouse/metabase-clickhouse-driver/commit/b1557fa570587adde8f5b19d7adea46d4c71d47d) in 1.50.4 when inserting missing values.
> Fix NPE on inserting missing values

- CHANGELOG.md
- resources/metabase-plugin.yaml
- src/metabase/driver/clickhouse.clj
- test/metabase/driver/clickhouse_test.clj
- test/metabase/test/data/clickhouse.clj
Adds a convenience configuration field (under the "advanced options", hidden by default) to override certain ClickHouse settings:
Resolves #271
> Easier configuration of custom ClickHouse settings

- src/metabase/driver/clickhouse.clj
- test/metabase/driver/clickhouse_impersonation_test.clj
- test/metabase/driver/clickhouse_test.clj
- test/metabase/test/data/clickhouse.clj
This PR started as future proofing for an upcoming HoneySQL update which requires explicit quoting of identifiers in some cases.
As part of this work I got the main Metabase upload's test suite running against the driver. This required some updates to the driver to track interface changes, and also revealed some small bugs, which have also been fixed.
~~**NOTE: this version will not be safe for v50 without further changes.**~~ Confirmed that this works with the upcoming version of v50.
> Fix support for Metabase CI and future-proof DDL statements

- .github/workflows/check.yml
- deps.edn
- docker-compose.yml
- resources/metabase-plugin.yaml
- src/metabase/driver/clickhouse.clj
- src/metabase/driver/clickhouse_introspection.clj
- src/metabase/driver/clickhouse_qp.clj
- src/metabase/driver/clickhouse_version.clj
- test/metabase/driver/clickhouse_data_types_test.clj
- test/metabase/driver/clickhouse_impersonation_test.clj
- test/metabase/driver/clickhouse_introspection_test.clj
- test/metabase/driver/clickhouse_test.clj
- test/metabase/test/data/clickhouse.clj
- test/metabase/test/data/datasets.sql
- Support JDBC v2 ([0.7.2](https://github.com/ClickHouse/clickhouse-java/releases/tag/v0.7.2))
- Metabase 52.x + Java 21 CI (closes #276)
- Hopefully fixes the timezones issues (again) - related to #200 
- `:convert-timezone` feature is disabled for now. This feature looks like it is intended to be used with "wall clock" types, but we always have timezone information in ClickHouse by design; it's incredibly difficult to make the MB tests work in this case, and I am not sure that it is going to work properly with CH.
- Added `max-open-connections` configuration option; default is 100.
The CI uses a fork again (see https://github.com/metabase/metabase/compare/v1.52.2.5...slvrtrn:metabase:0.52.x-ch); we've come a full circle. A few tests fail: 
- Unclear how …
> Update the driver to use JDBC v2

- CHANGELOG.md
- deps.edn
Version 0.8.0 that we currently use has a bug [1] that manifests itself as an error when trying to execute queries that contain common table expressions.
[1] https://github.com/ClickHouse/clickhouse-java/issues/2132
Fixes #288 and #297
> fix: Update clickhouse-client version to 0.8.1

- CHANGELOG.md
- resources/metabase-plugin.yaml
- src/metabase/driver/clickhouse.clj
- test/metabase/driver/clickhouse_test.clj
- test/metabase/test/data/clickhouse.clj
While that was not technically correct and it was not an expected behavior, previously, it was possible to specify something like `http://myhost` in the `host` configuration option. This PR brings back the old behavior.
> 1.53.3: Remove http/https schema from the host config

- .github/workflows/check.yml
- CHANGELOG.md
- deps.edn
- test/metabase/driver/clickhouse_data_types_test.clj
- test/metabase/test/data/clickhouse.clj
- Bumps JDBC to 0.8.2. This increases CSV uploads performance, as there were insert performance issues in 0.8.1
- There is an issue with test data loading in 0.8.2; a few tests are currently disabled because of that. Those tests should be re-enabled once a fixed JDBC version is out.
> Bump JDBC to 0.8.2

- deps.edn
Bump ClickHouse JDBC driver version to 0.8.4.
Delete items not relevant to your PR:
> Bump jdbc to 0.8.4
