- src/metabase/driver/clickhouse.clj
- test/metabase/test/data/clickhouse.clj
> Emulate Time data type

- LICENSE
- README.md
* Simplify README
* License AGPL, since driver is based on Metabase proper which uses AGPL
> Improve README

- src/metabase/driver/clickhouse.clj
- test/metabase/driver/clickhouse_test.clj
> Display Arrays

- .circleci/config.yml
- project.clj
- src/metabase/driver/clickhouse.clj
- test/metabase/driver/clickhouse_test.clj
- test/metabase/test/data/clickhouse.clj
> Test for (non-) empty String

- src/metabase/driver/clickhouse.clj
Implement driver method introduced with metabase/metabase#10303
Fix for #22
> Implement driver/date-add

- src/metabase/driver/clickhouse.clj
Catch up with upstream metabase/metabase#10561
> Improve group by year

- src/metabase/driver/clickhouse.clj
- test/metabase/driver/clickhouse_test.clj
> Enum Database Types Without Values

- project.clj
- src/metabase/driver/clickhouse.clj
- test/metabase/driver/clickhouse_test.clj
> Update for Metabase 0.38

- src/metabase/driver/clickhouse.clj
> fix comparison with Date fields

- deps.edn
- docker-compose.yml
- resources/metabase-plugin.yaml
> Add SSH tunnel option, bump CH docker container version

- src/metabase/driver/clickhouse.clj
- test/metabase/driver/clickhouse_test.clj
- test/metabase/driver/clickhouse_test_utils.clj
> Fix issue #133 with boolean columns

- resources/metabase-plugin.yaml
Add contact information for the partner information block (will substitute "our partner")
> Add plugin contact-info

- .docker/clickhouse/single_node_tls/Dockerfile
- .github/workflows/check.yml
- CHANGELOG.md
- docker-compose.yml
- resources/metabase-plugin.yaml
- src/metabase/driver/clickhouse.clj
- test/metabase/driver/clickhouse_test.clj
- test/metabase/driver/clickhouse_test_utils.clj
- test/metabase/test/data/clickhouse.clj
* Resolves #156 
* Bump ClickHouse to 23.4
* Bump Metabase to 0.46.2
> Fix sum-where with Int columns

- CHANGELOG.md
- deps.edn
- resources/metabase-plugin.yaml
- src/metabase/driver/clickhouse.clj
- test/metabase/test/data/clickhouse.clj
> Upgrade JDBC driver to 0.4.6

- .github/workflows/check.yml
- CHANGELOG.md
- README.md
- docker-compose.yml
- resources/metabase-plugin.yaml
- src/metabase/driver/clickhouse.clj
- test/metabase/driver/clickhouse_test.clj
- test/metabase/test/data/clickhouse.clj
> Add 0.47.7 question -> SQL conversion fix

- CHANGELOG.md
- README.md
- resources/metabase-plugin.yaml
- src/metabase/driver/clickhouse.clj
- src/metabase/driver/clickhouse_qp.clj
- test/metabase/test/data/clickhouse.clj
> Added `:datetime-diff` function support

- CHANGELOG.md
- README.md
- docker-compose.yml
- resources/metabase-plugin.yaml
- src/metabase/driver/clickhouse.clj
- src/metabase/driver/clickhouse_qp.clj
- test/metabase/driver/clickhouse_test.clj
- test/metabase/test/data/clickhouse.clj
> Fix incorrect UInt8 arrays serialization

- .gitignore
- CHANGELOG.md
- resources/metabase-plugin.yaml
- src/metabase/driver/clickhouse.clj
- test/metabase/driver/clickhouse_test.clj
- test/metabase/test/data/clickhouse.clj
- test/metabase/test/data/datasets.sql
Resolves https://github.com/ClickHouse/metabase-clickhouse-driver/issues/215
> Fix a connection issue with TLS and multiple databases

- .github/workflows/check.yml
- docker-compose.yml
- resources/metabase-plugin.yaml
- src/metabase/driver/clickhouse.clj
- test/metabase/test/data/clickhouse.clj
Fixed incorrect `product_name` passed to the JDBC driver (`metabase/1.5.0` -> `metabase/1.50.1`).
> Fix product_name passed to the JDBC driver

- CHANGELOG.md
- resources/metabase-plugin.yaml
- src/metabase/driver/clickhouse.clj
- src/metabase/driver/clickhouse_qp.clj
- test/metabase/driver/clickhouse_data_types_test.clj
- test/metabase/test/data/clickhouse.clj
- test/metabase/test/data/clickhouse_datasets.sql
> Fix unsigned integers, prepare 1.53.1

- CHANGELOG.md
- resources/metabase-plugin.yaml
- src/metabase/driver/clickhouse.clj
- test/metabase/test/data/clickhouse.clj
> Prepare 1.53.2
